version: '3.8'

networks:
  default:
    external: true
    name: future-devs
services:
  app:
    hostname: sas-university-classes
    container_name: sas-university-classes
    volumes:
      - ../../:/workspaces
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
